name: CI

on:
  push:
    branches: [main]
  pull_request:

defaults:
  run:
    working-directory: module.1
    shell: bash

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: module.1/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run Prettier check
        run: npx prettier --check .

  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: module.1/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test:run

  playwright:
    name: Playwright E2E
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.56.0-noble
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Start web server
        run: |
          npm run serve & echo $! > server.pid
      - name: Wait for server
        run: npx wait-on http://127.0.0.1:5000
      - name: Run E2E tests
        run: npm run test:e2e
      - name: Stop web server
        if: always()
        run: |
          if [ -f server.pid ]; then kill $(cat server.pid) || true; fi
